# ===================================================================
# Spring Boot configuration for the "prod" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

spring:
    profiles:
        active: prod
    devtools:
        restart:
            enabled: false
        livereload:
            enabled: false
    data:
        mongodb:
            uri: mongodb://localhost:27017
            database: cactusMaven
    mail:
        host: smtp.gmail.com
        port: 587
        username: cactus.activation@gmail.com  #Replace this field with your Gmail username.
        password: sitgesca23                   #Replace this field with your Gmail password.
        protocol: smtp
        tls: true
        properties.mail.smtp:
            auth: true
            starttls.enable: true
            ssl.trust: smtp.gmail.com
    thymeleaf:
        cache: true

liquibase:
    contexts: prod

server:
    port: 8080
    compression:
        enabled: true
        mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json

# ===================================================================
# JHipster specific properties
# ===================================================================

jhipster:
    http:
        cache: # Used by the CachingHttpHeadersFilter
            timeToLiveInDays: 31
    mail: # specific JHipster mail property, for standard properties see MailProperties
        from: cactus.activation@gmail.com
    metrics: # DropWizard Metrics configuration, used by MetricsConfiguration
        jmx.enabled: true
        spark:
            enabled: false
            host: localhost
            port: 9999
        graphite:
            enabled: false
            host: localhost
            port: 2003
            prefix: cactusMaven
